service: dotzip-nest-backend

frameworkVersion: v3

provider:
    name: aws
    region: ap-northeast-2
    runtime: nodejs20.x
    ecr:
        scanOnPush: true
        images:
            appimage:
            uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/dotzip:latest
            # file: Dockerfile

functions:
    api:
        name: dotzip-backend-lambda
        image:
            name: appimage
        timeout: 10
        memorySize: 512

plugins:
    - serverless-plugin-warmup

custom:
    warmup:
        officeHoursWarmer:
            enabled: true
            events:
                - schedule: cron(*/5 * * * ? *)
            concurrency: 1
            verbose: true
            prewarm: true
            payload:
                path: /dev/health
                method: GET
