service: dotzip-nest-backend

provider:
    name: aws
    region: ap-northeast-2
    runtime: nodejs20.x
    ecr:
        scanOnPush: true
        images:
            appimage:
            uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/dotzip:latest
            # file: Dockerfile

functions:
    api:
        image:
            name: appimage
        timeout: 10
        memorySize: 512

plugins:
    - serverless-plugin-warmup

custom:
    warmup:
        default:
            enabled: true
            events:
                - schedule: rate(5 minutes)
        prewarm: true
        payload:
            path: /health
            httpMethod: GET
